# Generated by Django 2.0.5 on 2019-09-20 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=100)),
                ('lname', models.CharField(max_length=100)),
                ('date_of_b', models.DateField(blank=True, null=True)),
                ('date_of_d', models.DateField(blank=True, null=True, verbose_name='Died')),
            ],
        ),
    ]
